version: '3.8'

services:
  agent-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_TOPIC_NAME=${KAFKA_TOPIC_NAME}
      - KAFKA_GROUP_ID_PREFIX=${KAFKA_GROUP_ID_PREFIX}
      - PORT=${PORT}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_URL=${PINECONE_INDEX_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_GENERATE_ENDPOINT=${GEMINI_GENERATE_ENDPOINT}
      - GEMINI_EMBEDDING_ENDPOINT=${GEMINI_EMBEDDING_ENDPOINT}
      
    volumes:
      - ./src:/usr/src/app/src
      - ./src/data:/usr/src/app/src/data
      - ./scripts:/usr/src/app/scripts
    restart: unless-stopped