version: '3.8'

services:
  agent-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      # Pinecone settings
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      # Other services configuration
      - LLM_API_KEY=${LLM_API_KEY}
      - EMBEDDING_API_KEY=${EMBEDDING_API_KEY}
      # Kafka settings (if used)
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    volumes:
      - ./src:/usr/src/app/src
      - ./src/data:/usr/src/app/src/data
      - ./scripts:/usr/src/app/scripts
    restart: unless-stopped